/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.collector.jsonc --include-runtime=false --strict-vars=false --env-interface=CollectorEnv src/collector-env.d.ts` (hash: 618ec79f3c49f8f1e36b92a4c38b4252)
interface __BaseEnv_CollectorEnv {
	AI_TRACKER_URL: string;
	TRACKED_HOST: string;
	INGEST_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./collector");
	}
	interface Env extends __BaseEnv_CollectorEnv {}
}
interface CollectorEnv extends __BaseEnv_CollectorEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_TRACKER_URL" | "TRACKED_HOST" | "INGEST_TOKEN">> {}
}
